// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: extensions/filters/v1/http/rbac/rbac.proto

package rbacv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RBAC_Action int32

const (
	RBAC_ALLOW RBAC_Action = 0
	RBAC_DENY  RBAC_Action = 1
)

// Enum value maps for RBAC_Action.
var (
	RBAC_Action_name = map[int32]string{
		0: "ALLOW",
		1: "DENY",
	}
	RBAC_Action_value = map[string]int32{
		"ALLOW": 0,
		"DENY":  1,
	}
)

func (x RBAC_Action) Enum() *RBAC_Action {
	p := new(RBAC_Action)
	*p = x
	return p
}

func (x RBAC_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RBAC_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_extensions_filters_v1_http_rbac_rbac_proto_enumTypes[0].Descriptor()
}

func (RBAC_Action) Type() protoreflect.EnumType {
	return &file_extensions_filters_v1_http_rbac_rbac_proto_enumTypes[0]
}

func (x RBAC_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RBAC_Action.Descriptor instead.
func (RBAC_Action) EnumDescriptor() ([]byte, []int) {
	return file_extensions_filters_v1_http_rbac_rbac_proto_rawDescGZIP(), []int{0, 0}
}

type RBAC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        RBAC_Action            `protobuf:"varint,1,opt,name=action,proto3,enum=extensions.filters.http.rbac.v1.RBAC_Action" json:"action,omitempty"`
	Rules         []*Rule                `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RBAC) Reset() {
	*x = RBAC{}
	mi := &file_extensions_filters_v1_http_rbac_rbac_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RBAC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RBAC) ProtoMessage() {}

func (x *RBAC) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_filters_v1_http_rbac_rbac_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RBAC.ProtoReflect.Descriptor instead.
func (*RBAC) Descriptor() ([]byte, []int) {
	return file_extensions_filters_v1_http_rbac_rbac_proto_rawDescGZIP(), []int{0}
}

func (x *RBAC) GetAction() RBAC_Action {
	if x != nil {
		return x.Action
	}
	return RBAC_ALLOW
}

func (x *RBAC) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*Source              `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	When          []*Condition           `protobuf:"bytes,2,rep,name=when,proto3" json:"when,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_extensions_filters_v1_http_rbac_rbac_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_filters_v1_http_rbac_rbac_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_extensions_filters_v1_http_rbac_rbac_proto_rawDescGZIP(), []int{1}
}

func (x *Rule) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *Rule) GetWhen() []*Condition {
	if x != nil {
		return x.When
	}
	return nil
}

type Source struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestPrincipals []string               `protobuf:"bytes,1,rep,name=request_principals,json=requestPrincipals,proto3" json:"request_principals,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_extensions_filters_v1_http_rbac_rbac_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_filters_v1_http_rbac_rbac_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_extensions_filters_v1_http_rbac_rbac_proto_rawDescGZIP(), []int{2}
}

func (x *Source) GetRequestPrincipals() []string {
	if x != nil {
		return x.RequestPrincipals
	}
	return nil
}

type Condition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	NotValues     []string               `protobuf:"bytes,3,rep,name=not_values,json=notValues,proto3" json:"not_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_extensions_filters_v1_http_rbac_rbac_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_filters_v1_http_rbac_rbac_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_extensions_filters_v1_http_rbac_rbac_proto_rawDescGZIP(), []int{3}
}

func (x *Condition) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Condition) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Condition) GetNotValues() []string {
	if x != nil {
		return x.NotValues
	}
	return nil
}

var File_extensions_filters_v1_http_rbac_rbac_proto protoreflect.FileDescriptor

const file_extensions_filters_v1_http_rbac_rbac_proto_rawDesc = "" +
	"\n" +
	"*extensions/filters/v1/http/rbac/rbac.proto\x12\x1fextensions.filters.http.rbac.v1\"\xa8\x01\n" +
	"\x04RBAC\x12D\n" +
	"\x06action\x18\x01 \x01(\x0e2,.extensions.filters.http.rbac.v1.RBAC.ActionR\x06action\x12;\n" +
	"\x05rules\x18\x02 \x03(\v2%.extensions.filters.http.rbac.v1.RuleR\x05rules\"\x1d\n" +
	"\x06Action\x12\t\n" +
	"\x05ALLOW\x10\x00\x12\b\n" +
	"\x04DENY\x10\x01\"\x89\x01\n" +
	"\x04Rule\x12A\n" +
	"\asources\x18\x01 \x03(\v2'.extensions.filters.http.rbac.v1.SourceR\asources\x12>\n" +
	"\x04when\x18\x02 \x03(\v2*.extensions.filters.http.rbac.v1.ConditionR\x04when\"7\n" +
	"\x06Source\x12-\n" +
	"\x12request_principals\x18\x01 \x03(\tR\x11requestPrincipals\"T\n" +
	"\tCondition\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\x12\x1d\n" +
	"\n" +
	"not_values\x18\x03 \x03(\tR\tnotValuesBBZ@github.com/kdubbo/xds-api/extensions/filters/v1/http/rbac;rbacv1b\x06proto3"

var (
	file_extensions_filters_v1_http_rbac_rbac_proto_rawDescOnce sync.Once
	file_extensions_filters_v1_http_rbac_rbac_proto_rawDescData []byte
)

func file_extensions_filters_v1_http_rbac_rbac_proto_rawDescGZIP() []byte {
	file_extensions_filters_v1_http_rbac_rbac_proto_rawDescOnce.Do(func() {
		file_extensions_filters_v1_http_rbac_rbac_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extensions_filters_v1_http_rbac_rbac_proto_rawDesc), len(file_extensions_filters_v1_http_rbac_rbac_proto_rawDesc)))
	})
	return file_extensions_filters_v1_http_rbac_rbac_proto_rawDescData
}

var file_extensions_filters_v1_http_rbac_rbac_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_extensions_filters_v1_http_rbac_rbac_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_extensions_filters_v1_http_rbac_rbac_proto_goTypes = []any{
	(RBAC_Action)(0),  // 0: extensions.filters.http.rbac.v1.RBAC.Action
	(*RBAC)(nil),      // 1: extensions.filters.http.rbac.v1.RBAC
	(*Rule)(nil),      // 2: extensions.filters.http.rbac.v1.Rule
	(*Source)(nil),    // 3: extensions.filters.http.rbac.v1.Source
	(*Condition)(nil), // 4: extensions.filters.http.rbac.v1.Condition
}
var file_extensions_filters_v1_http_rbac_rbac_proto_depIdxs = []int32{
	0, // 0: extensions.filters.http.rbac.v1.RBAC.action:type_name -> extensions.filters.http.rbac.v1.RBAC.Action
	2, // 1: extensions.filters.http.rbac.v1.RBAC.rules:type_name -> extensions.filters.http.rbac.v1.Rule
	3, // 2: extensions.filters.http.rbac.v1.Rule.sources:type_name -> extensions.filters.http.rbac.v1.Source
	4, // 3: extensions.filters.http.rbac.v1.Rule.when:type_name -> extensions.filters.http.rbac.v1.Condition
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_extensions_filters_v1_http_rbac_rbac_proto_init() }
func file_extensions_filters_v1_http_rbac_rbac_proto_init() {
	if File_extensions_filters_v1_http_rbac_rbac_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extensions_filters_v1_http_rbac_rbac_proto_rawDesc), len(file_extensions_filters_v1_http_rbac_rbac_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extensions_filters_v1_http_rbac_rbac_proto_goTypes,
		DependencyIndexes: file_extensions_filters_v1_http_rbac_rbac_proto_depIdxs,
		EnumInfos:         file_extensions_filters_v1_http_rbac_rbac_proto_enumTypes,
		MessageInfos:      file_extensions_filters_v1_http_rbac_rbac_proto_msgTypes,
	}.Build()
	File_extensions_filters_v1_http_rbac_rbac_proto = out.File
	file_extensions_filters_v1_http_rbac_rbac_proto_goTypes = nil
	file_extensions_filters_v1_http_rbac_rbac_proto_depIdxs = nil
}
