// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: route/v1/route_components.proto

package routev1

import (
	v1 "github.com/kdubbo/xds-api/type/matcher/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VirtualHost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Domains       []string               `protobuf:"bytes,2,rep,name=domains,proto3" json:"domains,omitempty"`
	Routes        []*Route               `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualHost) Reset() {
	*x = VirtualHost{}
	mi := &file_route_v1_route_components_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualHost) ProtoMessage() {}

func (x *VirtualHost) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_route_components_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualHost.ProtoReflect.Descriptor instead.
func (*VirtualHost) Descriptor() ([]byte, []int) {
	return file_route_v1_route_components_proto_rawDescGZIP(), []int{0}
}

func (x *VirtualHost) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VirtualHost) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *VirtualHost) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type Route struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Match *RouteMatch            `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*Route_Route
	//	*Route_NonForwardingAction
	Action        isRoute_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_route_v1_route_components_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_route_components_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_route_v1_route_components_proto_rawDescGZIP(), []int{1}
}

func (x *Route) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Route) GetMatch() *RouteMatch {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *Route) GetAction() isRoute_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *Route) GetRoute() *RouteAction {
	if x != nil {
		if x, ok := x.Action.(*Route_Route); ok {
			return x.Route
		}
	}
	return nil
}

func (x *Route) GetNonForwardingAction() *NonForwardingAction {
	if x != nil {
		if x, ok := x.Action.(*Route_NonForwardingAction); ok {
			return x.NonForwardingAction
		}
	}
	return nil
}

type isRoute_Action interface {
	isRoute_Action()
}

type Route_Route struct {
	Route *RouteAction `protobuf:"bytes,3,opt,name=route,proto3,oneof"`
}

type Route_NonForwardingAction struct {
	NonForwardingAction *NonForwardingAction `protobuf:"bytes,7,opt,name=non_forwarding_action,json=nonForwardingAction,proto3,oneof"`
}

func (*Route_Route) isRoute_Action() {}

func (*Route_NonForwardingAction) isRoute_Action() {}

type NonForwardingAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonForwardingAction) Reset() {
	*x = NonForwardingAction{}
	mi := &file_route_v1_route_components_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonForwardingAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonForwardingAction) ProtoMessage() {}

func (x *NonForwardingAction) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_route_components_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonForwardingAction.ProtoReflect.Descriptor instead.
func (*NonForwardingAction) Descriptor() ([]byte, []int) {
	return file_route_v1_route_components_proto_rawDescGZIP(), []int{2}
}

type WeightedCluster struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Clusters      []*WeightedCluster_ClusterWeight `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	TotalWeight   *wrapperspb.UInt32Value          `protobuf:"bytes,2,opt,name=total_weight,json=totalWeight,proto3" json:"total_weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeightedCluster) Reset() {
	*x = WeightedCluster{}
	mi := &file_route_v1_route_components_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeightedCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightedCluster) ProtoMessage() {}

func (x *WeightedCluster) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_route_components_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightedCluster.ProtoReflect.Descriptor instead.
func (*WeightedCluster) Descriptor() ([]byte, []int) {
	return file_route_v1_route_components_proto_rawDescGZIP(), []int{3}
}

func (x *WeightedCluster) GetClusters() []*WeightedCluster_ClusterWeight {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *WeightedCluster) GetTotalWeight() *wrapperspb.UInt32Value {
	if x != nil {
		return x.TotalWeight
	}
	return nil
}

type RouteMatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to PathSpecifier:
	//
	//	*RouteMatch_Prefix
	//	*RouteMatch_Path
	//	*RouteMatch_SafeRegex
	PathSpecifier isRouteMatch_PathSpecifier `protobuf_oneof:"path_specifier"`
	Headers       []*HeaderMatcher           `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteMatch) Reset() {
	*x = RouteMatch{}
	mi := &file_route_v1_route_components_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteMatch) ProtoMessage() {}

func (x *RouteMatch) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_route_components_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteMatch.ProtoReflect.Descriptor instead.
func (*RouteMatch) Descriptor() ([]byte, []int) {
	return file_route_v1_route_components_proto_rawDescGZIP(), []int{4}
}

func (x *RouteMatch) GetPathSpecifier() isRouteMatch_PathSpecifier {
	if x != nil {
		return x.PathSpecifier
	}
	return nil
}

func (x *RouteMatch) GetPrefix() string {
	if x != nil {
		if x, ok := x.PathSpecifier.(*RouteMatch_Prefix); ok {
			return x.Prefix
		}
	}
	return ""
}

func (x *RouteMatch) GetPath() string {
	if x != nil {
		if x, ok := x.PathSpecifier.(*RouteMatch_Path); ok {
			return x.Path
		}
	}
	return ""
}

func (x *RouteMatch) GetSafeRegex() *v1.RegexMatcher {
	if x != nil {
		if x, ok := x.PathSpecifier.(*RouteMatch_SafeRegex); ok {
			return x.SafeRegex
		}
	}
	return nil
}

func (x *RouteMatch) GetHeaders() []*HeaderMatcher {
	if x != nil {
		return x.Headers
	}
	return nil
}

type isRouteMatch_PathSpecifier interface {
	isRouteMatch_PathSpecifier()
}

type RouteMatch_Prefix struct {
	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3,oneof"`
}

type RouteMatch_Path struct {
	Path string `protobuf:"bytes,2,opt,name=path,proto3,oneof"`
}

type RouteMatch_SafeRegex struct {
	SafeRegex *v1.RegexMatcher `protobuf:"bytes,10,opt,name=safe_regex,json=safeRegex,proto3,oneof"`
}

func (*RouteMatch_Prefix) isRouteMatch_PathSpecifier() {}

func (*RouteMatch_Path) isRouteMatch_PathSpecifier() {}

func (*RouteMatch_SafeRegex) isRouteMatch_PathSpecifier() {}

type HeaderMatcher struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to HeaderMatchSpecifier:
	//
	//	*HeaderMatcher_ExactMatch
	//	*HeaderMatcher_PrefixMatch
	//	*HeaderMatcher_SafeRegexMatch
	HeaderMatchSpecifier isHeaderMatcher_HeaderMatchSpecifier `protobuf_oneof:"header_match_specifier"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HeaderMatcher) Reset() {
	*x = HeaderMatcher{}
	mi := &file_route_v1_route_components_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderMatcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderMatcher) ProtoMessage() {}

func (x *HeaderMatcher) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_route_components_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderMatcher.ProtoReflect.Descriptor instead.
func (*HeaderMatcher) Descriptor() ([]byte, []int) {
	return file_route_v1_route_components_proto_rawDescGZIP(), []int{5}
}

func (x *HeaderMatcher) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HeaderMatcher) GetHeaderMatchSpecifier() isHeaderMatcher_HeaderMatchSpecifier {
	if x != nil {
		return x.HeaderMatchSpecifier
	}
	return nil
}

func (x *HeaderMatcher) GetExactMatch() string {
	if x != nil {
		if x, ok := x.HeaderMatchSpecifier.(*HeaderMatcher_ExactMatch); ok {
			return x.ExactMatch
		}
	}
	return ""
}

func (x *HeaderMatcher) GetPrefixMatch() string {
	if x != nil {
		if x, ok := x.HeaderMatchSpecifier.(*HeaderMatcher_PrefixMatch); ok {
			return x.PrefixMatch
		}
	}
	return ""
}

func (x *HeaderMatcher) GetSafeRegexMatch() *v1.RegexMatcher {
	if x != nil {
		if x, ok := x.HeaderMatchSpecifier.(*HeaderMatcher_SafeRegexMatch); ok {
			return x.SafeRegexMatch
		}
	}
	return nil
}

type isHeaderMatcher_HeaderMatchSpecifier interface {
	isHeaderMatcher_HeaderMatchSpecifier()
}

type HeaderMatcher_ExactMatch struct {
	ExactMatch string `protobuf:"bytes,4,opt,name=exact_match,json=exactMatch,proto3,oneof"`
}

type HeaderMatcher_PrefixMatch struct {
	PrefixMatch string `protobuf:"bytes,9,opt,name=prefix_match,json=prefixMatch,proto3,oneof"`
}

type HeaderMatcher_SafeRegexMatch struct {
	SafeRegexMatch *v1.RegexMatcher `protobuf:"bytes,11,opt,name=safe_regex_match,json=safeRegexMatch,proto3,oneof"`
}

func (*HeaderMatcher_ExactMatch) isHeaderMatcher_HeaderMatchSpecifier() {}

func (*HeaderMatcher_PrefixMatch) isHeaderMatcher_HeaderMatchSpecifier() {}

func (*HeaderMatcher_SafeRegexMatch) isHeaderMatcher_HeaderMatchSpecifier() {}

type RouteAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ClusterSpecifier:
	//
	//	*RouteAction_Cluster
	//	*RouteAction_WeightedClusters
	ClusterSpecifier isRouteAction_ClusterSpecifier `protobuf_oneof:"cluster_specifier"`
	Timeout          *durationpb.Duration           `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RouteAction) Reset() {
	*x = RouteAction{}
	mi := &file_route_v1_route_components_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteAction) ProtoMessage() {}

func (x *RouteAction) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_route_components_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteAction.ProtoReflect.Descriptor instead.
func (*RouteAction) Descriptor() ([]byte, []int) {
	return file_route_v1_route_components_proto_rawDescGZIP(), []int{6}
}

func (x *RouteAction) GetClusterSpecifier() isRouteAction_ClusterSpecifier {
	if x != nil {
		return x.ClusterSpecifier
	}
	return nil
}

func (x *RouteAction) GetCluster() string {
	if x != nil {
		if x, ok := x.ClusterSpecifier.(*RouteAction_Cluster); ok {
			return x.Cluster
		}
	}
	return ""
}

func (x *RouteAction) GetWeightedClusters() *WeightedCluster {
	if x != nil {
		if x, ok := x.ClusterSpecifier.(*RouteAction_WeightedClusters); ok {
			return x.WeightedClusters
		}
	}
	return nil
}

func (x *RouteAction) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type isRouteAction_ClusterSpecifier interface {
	isRouteAction_ClusterSpecifier()
}

type RouteAction_Cluster struct {
	Cluster string `protobuf:"bytes,1,opt,name=cluster,proto3,oneof"`
}

type RouteAction_WeightedClusters struct {
	WeightedClusters *WeightedCluster `protobuf:"bytes,3,opt,name=weighted_clusters,json=weightedClusters,proto3,oneof"`
}

func (*RouteAction_Cluster) isRouteAction_ClusterSpecifier() {}

func (*RouteAction_WeightedClusters) isRouteAction_ClusterSpecifier() {}

type WeightedCluster_ClusterWeight struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Weight        *wrapperspb.UInt32Value `protobuf:"bytes,2,opt,name=weight,proto3" json:"weight,omitempty"`
	ClusterHeader string                  `protobuf:"bytes,12,opt,name=cluster_header,json=clusterHeader,proto3" json:"cluster_header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeightedCluster_ClusterWeight) Reset() {
	*x = WeightedCluster_ClusterWeight{}
	mi := &file_route_v1_route_components_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeightedCluster_ClusterWeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightedCluster_ClusterWeight) ProtoMessage() {}

func (x *WeightedCluster_ClusterWeight) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_route_components_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightedCluster_ClusterWeight.ProtoReflect.Descriptor instead.
func (*WeightedCluster_ClusterWeight) Descriptor() ([]byte, []int) {
	return file_route_v1_route_components_proto_rawDescGZIP(), []int{3, 0}
}

func (x *WeightedCluster_ClusterWeight) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WeightedCluster_ClusterWeight) GetWeight() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Weight
	}
	return nil
}

func (x *WeightedCluster_ClusterWeight) GetClusterHeader() string {
	if x != nil {
		return x.ClusterHeader
	}
	return ""
}

var File_route_v1_route_components_proto protoreflect.FileDescriptor

const file_route_v1_route_components_proto_rawDesc = "" +
	"\n" +
	"\x1froute/v1/route_components.proto\x12\broute.v1\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1btype/matcher/v1/regex.proto\"d\n" +
	"\vVirtualHost\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\adomains\x18\x02 \x03(\tR\adomains\x12'\n" +
	"\x06routes\x18\x03 \x03(\v2\x0f.route.v1.RouteR\x06routes\"\xd5\x01\n" +
	"\x05Route\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x05match\x18\x02 \x01(\v2\x14.route.v1.RouteMatchR\x05match\x12-\n" +
	"\x05route\x18\x03 \x01(\v2\x15.route.v1.RouteActionH\x00R\x05route\x12S\n" +
	"\x15non_forwarding_action\x18\a \x01(\v2\x1d.route.v1.NonForwardingActionH\x00R\x13nonForwardingActionB\b\n" +
	"\x06action\"\x15\n" +
	"\x13NonForwardingAction\"\x9a\x02\n" +
	"\x0fWeightedCluster\x12C\n" +
	"\bclusters\x18\x01 \x03(\v2'.route.v1.WeightedCluster.ClusterWeightR\bclusters\x12?\n" +
	"\ftotal_weight\x18\x02 \x01(\v2\x1c.google.protobuf.UInt32ValueR\vtotalWeight\x1a\x80\x01\n" +
	"\rClusterWeight\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x06weight\x18\x02 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x06weight\x12%\n" +
	"\x0ecluster_header\x18\f \x01(\tR\rclusterHeader\"\xc1\x01\n" +
	"\n" +
	"RouteMatch\x12\x18\n" +
	"\x06prefix\x18\x01 \x01(\tH\x00R\x06prefix\x12\x14\n" +
	"\x04path\x18\x02 \x01(\tH\x00R\x04path\x12>\n" +
	"\n" +
	"safe_regex\x18\n" +
	" \x01(\v2\x1d.type.matcher.v1.RegexMatcherH\x00R\tsafeRegex\x121\n" +
	"\aheaders\x18\x06 \x03(\v2\x17.route.v1.HeaderMatcherR\aheadersB\x10\n" +
	"\x0epath_specifier\"\xd0\x01\n" +
	"\rHeaderMatcher\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\vexact_match\x18\x04 \x01(\tH\x00R\n" +
	"exactMatch\x12#\n" +
	"\fprefix_match\x18\t \x01(\tH\x00R\vprefixMatch\x12I\n" +
	"\x10safe_regex_match\x18\v \x01(\v2\x1d.type.matcher.v1.RegexMatcherH\x00R\x0esafeRegexMatchB\x18\n" +
	"\x16header_match_specifier\"\xbd\x01\n" +
	"\vRouteAction\x12\x1a\n" +
	"\acluster\x18\x01 \x01(\tH\x00R\acluster\x12H\n" +
	"\x11weighted_clusters\x18\x03 \x01(\v2\x19.route.v1.WeightedClusterH\x00R\x10weightedClusters\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeoutB\x13\n" +
	"\x11cluster_specifierB,Z*github.com/kdubbo/xds-api/route/v1;routev1b\x06proto3"

var (
	file_route_v1_route_components_proto_rawDescOnce sync.Once
	file_route_v1_route_components_proto_rawDescData []byte
)

func file_route_v1_route_components_proto_rawDescGZIP() []byte {
	file_route_v1_route_components_proto_rawDescOnce.Do(func() {
		file_route_v1_route_components_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_route_v1_route_components_proto_rawDesc), len(file_route_v1_route_components_proto_rawDesc)))
	})
	return file_route_v1_route_components_proto_rawDescData
}

var file_route_v1_route_components_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_route_v1_route_components_proto_goTypes = []any{
	(*VirtualHost)(nil),                   // 0: route.v1.VirtualHost
	(*Route)(nil),                         // 1: route.v1.Route
	(*NonForwardingAction)(nil),           // 2: route.v1.NonForwardingAction
	(*WeightedCluster)(nil),               // 3: route.v1.WeightedCluster
	(*RouteMatch)(nil),                    // 4: route.v1.RouteMatch
	(*HeaderMatcher)(nil),                 // 5: route.v1.HeaderMatcher
	(*RouteAction)(nil),                   // 6: route.v1.RouteAction
	(*WeightedCluster_ClusterWeight)(nil), // 7: route.v1.WeightedCluster.ClusterWeight
	(*wrapperspb.UInt32Value)(nil),        // 8: google.protobuf.UInt32Value
	(*v1.RegexMatcher)(nil),               // 9: type.matcher.v1.RegexMatcher
	(*durationpb.Duration)(nil),           // 10: google.protobuf.Duration
}
var file_route_v1_route_components_proto_depIdxs = []int32{
	1,  // 0: route.v1.VirtualHost.routes:type_name -> route.v1.Route
	4,  // 1: route.v1.Route.match:type_name -> route.v1.RouteMatch
	6,  // 2: route.v1.Route.route:type_name -> route.v1.RouteAction
	2,  // 3: route.v1.Route.non_forwarding_action:type_name -> route.v1.NonForwardingAction
	7,  // 4: route.v1.WeightedCluster.clusters:type_name -> route.v1.WeightedCluster.ClusterWeight
	8,  // 5: route.v1.WeightedCluster.total_weight:type_name -> google.protobuf.UInt32Value
	9,  // 6: route.v1.RouteMatch.safe_regex:type_name -> type.matcher.v1.RegexMatcher
	5,  // 7: route.v1.RouteMatch.headers:type_name -> route.v1.HeaderMatcher
	9,  // 8: route.v1.HeaderMatcher.safe_regex_match:type_name -> type.matcher.v1.RegexMatcher
	3,  // 9: route.v1.RouteAction.weighted_clusters:type_name -> route.v1.WeightedCluster
	10, // 10: route.v1.RouteAction.timeout:type_name -> google.protobuf.Duration
	8,  // 11: route.v1.WeightedCluster.ClusterWeight.weight:type_name -> google.protobuf.UInt32Value
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_route_v1_route_components_proto_init() }
func file_route_v1_route_components_proto_init() {
	if File_route_v1_route_components_proto != nil {
		return
	}
	file_route_v1_route_components_proto_msgTypes[1].OneofWrappers = []any{
		(*Route_Route)(nil),
		(*Route_NonForwardingAction)(nil),
	}
	file_route_v1_route_components_proto_msgTypes[4].OneofWrappers = []any{
		(*RouteMatch_Prefix)(nil),
		(*RouteMatch_Path)(nil),
		(*RouteMatch_SafeRegex)(nil),
	}
	file_route_v1_route_components_proto_msgTypes[5].OneofWrappers = []any{
		(*HeaderMatcher_ExactMatch)(nil),
		(*HeaderMatcher_PrefixMatch)(nil),
		(*HeaderMatcher_SafeRegexMatch)(nil),
	}
	file_route_v1_route_components_proto_msgTypes[6].OneofWrappers = []any{
		(*RouteAction_Cluster)(nil),
		(*RouteAction_WeightedClusters)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_route_v1_route_components_proto_rawDesc), len(file_route_v1_route_components_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_route_v1_route_components_proto_goTypes,
		DependencyIndexes: file_route_v1_route_components_proto_depIdxs,
		MessageInfos:      file_route_v1_route_components_proto_msgTypes,
	}.Build()
	File_route_v1_route_components_proto = out.File
	file_route_v1_route_components_proto_goTypes = nil
	file_route_v1_route_components_proto_depIdxs = nil
}
