// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: extensions/filters/v1/http/jwt_authn/jwt_authn.proto

package jwt_authnv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JwtAuthentication struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*JwtProvider         `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	AllowMissing  bool                   `protobuf:"varint,2,opt,name=allow_missing,json=allowMissing,proto3" json:"allow_missing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwtAuthentication) Reset() {
	*x = JwtAuthentication{}
	mi := &file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwtAuthentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtAuthentication) ProtoMessage() {}

func (x *JwtAuthentication) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtAuthentication.ProtoReflect.Descriptor instead.
func (*JwtAuthentication) Descriptor() ([]byte, []int) {
	return file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_rawDescGZIP(), []int{0}
}

func (x *JwtAuthentication) GetProviders() []*JwtProvider {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *JwtAuthentication) GetAllowMissing() bool {
	if x != nil {
		return x.AllowMissing
	}
	return false
}

type JwtProvider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Audiences     []string               `protobuf:"bytes,2,rep,name=audiences,proto3" json:"audiences,omitempty"`
	JwksUri       string                 `protobuf:"bytes,3,opt,name=jwks_uri,json=jwksUri,proto3" json:"jwks_uri,omitempty"`
	Jwks          string                 `protobuf:"bytes,4,opt,name=jwks,proto3" json:"jwks,omitempty"`
	FromHeaders   []*JwtHeader           `protobuf:"bytes,5,rep,name=from_headers,json=fromHeaders,proto3" json:"from_headers,omitempty"`
	FromParams    []string               `protobuf:"bytes,6,rep,name=from_params,json=fromParams,proto3" json:"from_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwtProvider) Reset() {
	*x = JwtProvider{}
	mi := &file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwtProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtProvider) ProtoMessage() {}

func (x *JwtProvider) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtProvider.ProtoReflect.Descriptor instead.
func (*JwtProvider) Descriptor() ([]byte, []int) {
	return file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_rawDescGZIP(), []int{1}
}

func (x *JwtProvider) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *JwtProvider) GetAudiences() []string {
	if x != nil {
		return x.Audiences
	}
	return nil
}

func (x *JwtProvider) GetJwksUri() string {
	if x != nil {
		return x.JwksUri
	}
	return ""
}

func (x *JwtProvider) GetJwks() string {
	if x != nil {
		return x.Jwks
	}
	return ""
}

func (x *JwtProvider) GetFromHeaders() []*JwtHeader {
	if x != nil {
		return x.FromHeaders
	}
	return nil
}

func (x *JwtProvider) GetFromParams() []string {
	if x != nil {
		return x.FromParams
	}
	return nil
}

type JwtHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwtHeader) Reset() {
	*x = JwtHeader{}
	mi := &file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwtHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtHeader) ProtoMessage() {}

func (x *JwtHeader) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtHeader.ProtoReflect.Descriptor instead.
func (*JwtHeader) Descriptor() ([]byte, []int) {
	return file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_rawDescGZIP(), []int{2}
}

func (x *JwtHeader) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JwtHeader) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

var File_extensions_filters_v1_http_jwt_authn_jwt_authn_proto protoreflect.FileDescriptor

const file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_rawDesc = "" +
	"\n" +
	"4extensions/filters/v1/http/jwt_authn/jwt_authn.proto\x12$extensions.filters.http.jwt_authn.v1\"\x89\x01\n" +
	"\x11JwtAuthentication\x12O\n" +
	"\tproviders\x18\x01 \x03(\v21.extensions.filters.http.jwt_authn.v1.JwtProviderR\tproviders\x12#\n" +
	"\rallow_missing\x18\x02 \x01(\bR\fallowMissing\"\xe7\x01\n" +
	"\vJwtProvider\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x12\x1c\n" +
	"\taudiences\x18\x02 \x03(\tR\taudiences\x12\x19\n" +
	"\bjwks_uri\x18\x03 \x01(\tR\ajwksUri\x12\x12\n" +
	"\x04jwks\x18\x04 \x01(\tR\x04jwks\x12R\n" +
	"\ffrom_headers\x18\x05 \x03(\v2/.extensions.filters.http.jwt_authn.v1.JwtHeaderR\vfromHeaders\x12\x1f\n" +
	"\vfrom_params\x18\x06 \x03(\tR\n" +
	"fromParams\"7\n" +
	"\tJwtHeader\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefixBLZJgithub.com/kdubbo/xds-api/extensions/filters/v1/http/jwt_authn;jwt_authnv1b\x06proto3"

var (
	file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_rawDescOnce sync.Once
	file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_rawDescData []byte
)

func file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_rawDescGZIP() []byte {
	file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_rawDescOnce.Do(func() {
		file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_rawDesc), len(file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_rawDesc)))
	})
	return file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_rawDescData
}

var file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_goTypes = []any{
	(*JwtAuthentication)(nil), // 0: extensions.filters.http.jwt_authn.v1.JwtAuthentication
	(*JwtProvider)(nil),       // 1: extensions.filters.http.jwt_authn.v1.JwtProvider
	(*JwtHeader)(nil),         // 2: extensions.filters.http.jwt_authn.v1.JwtHeader
}
var file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_depIdxs = []int32{
	1, // 0: extensions.filters.http.jwt_authn.v1.JwtAuthentication.providers:type_name -> extensions.filters.http.jwt_authn.v1.JwtProvider
	2, // 1: extensions.filters.http.jwt_authn.v1.JwtProvider.from_headers:type_name -> extensions.filters.http.jwt_authn.v1.JwtHeader
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_init() }
func file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_init() {
	if File_extensions_filters_v1_http_jwt_authn_jwt_authn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_rawDesc), len(file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_goTypes,
		DependencyIndexes: file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_depIdxs,
		MessageInfos:      file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_msgTypes,
	}.Build()
	File_extensions_filters_v1_http_jwt_authn_jwt_authn_proto = out.File
	file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_goTypes = nil
	file_extensions_filters_v1_http_jwt_authn_jwt_authn_proto_depIdxs = nil
}
